//
// Created by Gebruiker on 12/03/2020.
//

#ifndef PROJECT_KEYPRESSSURFACES_H
#define PROJECT_KEYPRESSSURFACES_H

#endif //PROJECT_KEYPRESSSURFACES_H
enum KeyPressSurfaces {
    KEY_PRESS_SURFACE_DEFAULT,
    KEY_PRESS_SURFACE_UP,
    KEY_PRESS_SURFACE_DOWN,
    KEY_PRESS_SURFACE_LEFT,
    KEY_PRESS_SURFACE_RIGHT,
    KEY_PRESS_SURFACE_TOTAL
};